name: iOS Build

on:
  push:
    branches: [ "masterz" ]
  pull_request:
    branches: [ "masterz" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
        
      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          
      - name: Build IPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r ios_release.ipa Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ios
          path: build/ios/iphoneos/ios_release.ipa